name: finplus
description: Finplus

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  ##internal packages
  commons:
    path: ./packages/commons
  firebase_remote_config: ^3.0.14
  firebase_core: ^2.7.1
  connectivity_plus: ^3.0.3
  internet_connection_checker: ^1.0.0+1
  dio: 5.1.0
  cryptography_flutter: ^2.2.0
  pinput: ^2.2.16
  flutter_native_splash: ^2.2.19
  json_annotation: ^4.8.1
  floor_annotation: ^1.4.2
  either_dart: ^0.4.0
  async: ^2.10.0
  file_picker: ^5.3.1
  pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.2.0
  web_socket_channel: ^2.4.0
  stomp_dart_client: ^1.0.2
  agora_uikit: ^1.3.7
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  floor_generator: ^1.4.2
  build_runner: ^2.1.2
  json_serializable: ^6.6.2
  retrofit_generator: ">=7.0.0 <8.0.0"
  flutter_gen_runner:

flutter_gen:
  output: lib/constant/

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Semibold.ttf
